### ISSUE TITLE
Control grid position

### ISSUE THREAD

**Issue by JDCalvert** [xaukael/macro-grid#1]
Hi there, I just found your module and love it! I have my normal macro bar in the default position on the left - would it be possible to add an option to choose the horizontal position, like there is for the vertical position please?

**Comment by xaukael** [comment]
Done in 1.0.2. Mind that it is a string for the left style not a number in pixels which should be obvious from the default value which centers it on the screen. You will want your value around 245px to approximate the usual hotbar position.

**Comment by JDCalvert** [comment]
That's excellent, thanks!
