### ISSUE TITLE
[Feature request] Accept dragging of non-macro entities and unimported macros into macro grid similar to default macro hotbar

### ISSUE THREAD

**Issue by pedrogrullada** [xaukael/macro-grid#3]
You can currently only drag already imported macros into macro grid, meaning if you wish to drag a non-macro entity like an item, journal, actor, or anything else for quick access the way you would with the default macro hotbar, nothing happens. Similarly, you can't drag a macro directly from your compendium into macro grid.

As it stands, you need to drag your non-macro entity into the regular hotbar for it to create the quick access macro and then you can drag it into macro grid from the macro directory, or in the case of unimported macros, you must import them first.

It'd be a great improvement if macro grid behaved the same as the default macro hotbar when it comes to dragging entities into it. Thanks for this module, it has saved me lots of time.

**Comment by xaukael** [comment]
The dragging from compendium, I added when I released v2. I added dragging of other documents in v2.1.0, but I changed it a little bit by taking the image from the document and make the name just the same as the document. Unfortunately, I cannot handle any custom drop behavior from any system or other module. It will be limited to just the sheet toggle behavior,
