### ISSUE TITLE
Macro Grid not displaying macro icons that display in the hot bar

### ISSUE THREAD

**Issue by Arbitrary1079** [xaukael/macro-grid#6]
Below is a screen grab of my hot bar:

![image](https://github.com/xaukael/macro-grid/assets/133781420/f4555496-a9d8-494d-a4f1-f450da99b04a)

But when I activate macro grid, it displays many of the slots as empty:

![image](https://github.com/xaukael/macro-grid/assets/133781420/df94422a-2408-4788-a35e-4cbc6923c087)

Clicking or right-clicking on any of the blank slots does nothing. I'm unable to edit them from macro grid. If I try to drag a macro from the macro library to a blank slot in macro grid it gives the error: "There is already a macro in this slot."

**Comment by xaukael** [comment]
any errors in the console (F12)? Suspicious that those that are not showing all have the same sort of images.

**Comment by xaukael** [comment]
problem was image with no default dimensions somehow. fixed in 2.0.2
