### ISSUE TITLE
[Bug] Sending messages or items to chat while macro grid is opened moves UI elements up

### ISSUE THREAD

**Issue by pedrogrullada** [xaukael/macro-grid#8]
Reproduced in the pf2e system

https://github.com/user-attachments/assets/fd266503-da6d-4e63-98be-2caaf710d73e

**Comment by xaukael** [comment]
image didn't load, but description was good enough. Shocked at how long it took for this to come up and even more shocked I never encountered it myself. Fixed in v2.1.1
